---
# OpenStack custom images for SUNET Platform

clean_workspace: true
git:
  branch: main
triggers:
  cron: "@daily"
builders:
  - docker

extra_jobs:
  # Keystone with OIDC support
  - name: openstack-keystone
    builders:
      - docker
    docker_name: platform/openstack-keystone
    docker_context_dir: keystone
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # OpenStack Operator (Kopf-based K8s operator)
  - name: openstack-operator
    builders:
      - docker
    docker_name: platform/openstack-operator
    docker_context_dir: openstack-operator
    docker_no_cache: true
    docker_tags:
      - "0.1.0"
      - "latest"

  # Libvirt with QEMU SPICE support
  - name: openstack-libvirt
    builders:
      - docker
    docker_name: platform/openstack-libvirt
    docker_context_dir: libvirt
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

